version: '3.9'

services:
 surrealdb:
    build: 
      context: ./db
      dockerfile: Dockerfile
    container_name: surrealdb-dc
    
    # environment variable loaded from allocated .env file
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    ports:
      - 10001:8000
    volumes:
      - './db:/usr/src/db'

    command: "start --user ${DB_USER} --pass ${DB_PASS} --log full file://usr/src/db"


  # server:
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile
  #   container_name: server
  #   restart: always
  #   ports:
  #     - 10000:10000
  #   volumes:
  #     - stripe-data:/usr/src/server/data
  #     - ./server:/usr/src/server
  #     - /usr/src/server/node_modules
  #   networks:
  #     - app_network
  #   environment:
  #     - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
  #     - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
  #     - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
  #     - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
  #     - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
  #     - RESET_PASSWORD_SECRET=${RESET_PASSWORD_SECRET}
  #     - EMAIL_VERIFICATION_SECRET=${EMAIL_VERIFICATION_SECRET}
  #     - EMAIL_UPDATE_SECRET=${EMAIL_UPDATE_SECRET} 
  #     - SMTP_USERNAME=${SMTP_USERNAME}
  #     - SMTP_PASSWORD=${SMTP_PASSWORD}
  #     - DATABASE_URL_HOST=${DATABASE_URL_HOST}
  #     - CLOUDINARY_URL=${CLOUDINARY_URL}
  #     - ACCOUNT_SID=${ACCOUNT_SID}
  #     - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
  #     - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}

  # nextjs-app:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   container_name: nextjs-app
  #   env_file:
  #     - .env.production
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - app_network








